name: comandero_flutter
description: App Comandix (movil/tablet)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  go_router: ^16.3.0
  fluttertoast: ^9.0.0
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.3.2
  syncfusion_flutter_core: ^31.2.4
  syncfusion_flutter_charts: ^31.2.4
  intl: ^0.20.2
  http: ^1.2.2
  dio: ^5.4.3+1
  socket_io_client: ^2.0.3+1
  path_provider: ^2.1.4
  open_file: ^3.5.0
  share_plus: ^10.1.2
  pdf: ^3.11.1
  printing: ^5.13.3
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  json_serializable: ^6.11.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ui_reference/
